### ISSUE TITLE
Move V1 kwargs to ColumnSharer

### ISSUE THREAD

**Issue by cchoquette** [georgianpartners/foreshadow#123]
https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3MjcwMjc5NTg0/pull_request_reviews/more_threads
convo: https://github.com/georgianpartners/foreshadow/pull/111#discussion_r310218494

**Comment by JingJZ160** [comment]
This no longer makes sense. Closing now. If we really encounter any issue, we will deal with it.
