### ISSUE TITLE
Integration Testing

### ISSUE THREAD

**Issue by cchoquette** [georgianpartners/foreshadow#131]
#### Description
Right now, testing for the full DataPreparer pipeline and Foreshadow pipeline is minimal. Many tests were as well disabled in the switch from V1 preprocessor to V2 DataPreparer. 

Guideline: V2 tests should be a superset of V1.

- [x] These tests need to be reenabled to ensure our functionality is sufficiently tested. Modify the tests if it only runs with V1 architecture.
- [x] We will also need to create additional tests for any V2 nuances that we encounter.

Estimate: 2 days.

**Comment by JingJZ160** [comment]
Done.
