### ISSUE TITLE
Add Integration test 

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#33]
#### Description
Add the following integration test to the framework
1 binary classification problem
1 multi-class classification problem
1 regression problem

We should check the model performance (F1 score for example) as well as the runtime performance. 
Although we could simply treat such integration test as unit test if they run quickly, unit test should not include long running test cases. Therefore, please investigate how to host such integration test as a separate step in CI/CD pipeline.

**Comment by robocoder99** [comment]
I implemented changing that setting via an environmental variable. The documentation will be updated to reflect that. We might want to change the datasets in use as I think that decision should be made between all of us, it is an easy switch though. Right now I have toy datasets and a threshold that it will stop passing tests after it falls past 10% performance (another easy to change threshold if we need).

**Comment by robocoder99** [comment]
Another consideration is if we ever want to use the full pipeline for the integration test. The pros are that it is more reflective of our full system which was designed to be used by auto-estimators and hyperparameter tuners but the cons are that it could take significant times to run these tests (on the order of ~12 hours per test to get a significant result)

**Comment by jichaogp** [comment]
Hi @robocoder99 , How did we implement the integration test? As unit test or as part of the pipeline?

**Comment by robocoder99** [comment]
The integration test is a test in pytest that is marked by a decorator as being a "slow" test. Slow tests are run by default but can be bypassed by setting an environmental variable. That way developers can set that variable and run tests quickly. The test trains the framework using its default settings on a test dataset and compares the value to a previously obtained value.
