### ISSUE TITLE
Basic command line driver

### ISSUE THREAD

**Issue by adithyabsk** [georgianpartners/foreshadow#43]
#### Description
* MLFlow (https://mlflow.org/docs/latest/quickstart.html)
* Custom rolled option

**Comment by jichaogp** [comment]
Hi @robocoder99, here is what I have thought about the requirements:

python foreshadow --data datafile.csv --target <target_column> -level[1,2,3] --method logistic_regression --time 30

--data specify the datafile in csv format (we can support other data format in the future)
--target the name of the column that will be used as the target. We will also infer whether this is a regression or classification problem from this column
--level a choice from 1,2, or 3 with default value 1. Level 1 means we are going to use the default Intent and the method specified by --method. Level 2 means we are going to do hyper-parameter search on all matched intent (Categorical, Numerical if both matches) but still use the method specified by --method. Level 3 means we are going to use the default Intent but use TPOT or auto-sklearn to explore models and hyper-parameters.
--method a method we will use when not involving TPOT and auto-sklear (level 1 and 2), default is logisticRegression for classification and LinearRegression for regression problem.
--time the time we allow TPOT and auto-sklearn to run. Default 10 minutes. If we can use this information to control the tuning in Level 2, that will be extra.
