### ISSUE TITLE
Shall Preprocessor json dump output SmartTransformer or concrete transformer?

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#51]
#### Description

Here is an example of the json dump of the preprocessor:

```json
{
    "columns": {
        "age": {
            "intent": "CategoricalIntent",
            "pipeline": [
                {
                    "transformer": "DropFeature",
                    "name": "dropper",
                    "parameters": {
                        "keep_columns": false,
                        "name": "dropper",
                        "raise_on_inverse": false,
                        "threshold": 0.3
                    }
                },
                {
                    "transformer": "Encoder",
                    "name": "impute_encode",
                    "parameters": {
                        "y_var": false,
                        "override": null,
                        "name": "impute_encode",
                        "keep_columns": false
                    }
                }
            ],
            "all_matched_intents": [
                "GenericIntent",
                "NumericIntent",
                "CategoricalIntent"
            ]
        },
       ...
}
```
From it, we can see the pipeline section lists SmartTransformers instead of the actual transformer selected by the SmartTransformer. There are several cons with this approach:

1. This means every time when we reuse the preprocessor json dump, the logic in SmartTransformer will be executed again to figure out the concrete transformer fit for each column. Consider an ideal workflow we have discussed (Start by let the framework to figure out the proper intent and pipeline for each column and a simple estimator to generate a baseline performance number, examine the pipeline and selectively add override in combination section to search different decisions based on domain knowledge, and finally use the fine tuned pipeline with an AutoEstimator for model exploration and model hyper-parameter tuning.), the current approach might cause lots of repetitive work in the second step. To be more specific, assuming we would like to search the 2 potential intents for 2 columns for a dataset with 20 columns, although we are willing to accept the pipeline for the other 18 columns as is, the logic for the SmartTransformer for each of those columns will be run 4 times. For large dataset with many columns and samples, especially if the space of combination to search is big, this could consume substantial amount of computation time.
2. As an end user, I would like to see the concrete transformer to inform myself what is actually happening while the json dump is not as explicit as expected.
3. Examples of preprocessor json dumps in our documentation often use concrete transformer. It could be surprising for external users to see the actual json dump they get is not the case.

We have discussed one counter argument so far, which is that this approach allows the SmartTransformer to adjust dynamically to the data fed to the framework every time it is used. On this point, I would argue that if the data changes so much that the concrete transformer need to change accordingly, there is a potential the selected intent need to change as well.

@adithyabsk @robocoder99 , please add your comment so that we can finalize a decision on this and move forward.

**Comment by robocoder99** [comment]
Upon further thought I am going to reverse my previous position on the topic. From my perspective, it is likely more beneficial for us to export the concrete transformer for the following reasons.

1) Exporting a smart-transformer and then optimizing it via the override parameter is redundant to simply optimizing by replacing the transformer entirely using the optimization system.

2) Any given serialized pipeline could only ever be assumed valid for samples of data from the same population. With the smart transformers we are making population-level assumptions and thus we should not expect the smart transformer choice to change over time as the model is re-trained and if it does change the model likely needs to be re-evaluated as a whole. 

3) As stated by @jichaogp, the clarity increases significantly.

**Comment by jichaogp** [comment]
I am closing this since Alex and I are aligned.
