### ISSUE TITLE
Collision of column names for HashingEncoder

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#8]
HashingEncoder does not use original column name or the name of a category to form new column names. The new column names from it is alwasy col_1, col_2 etc. If there are multiple columns picking up HashingEncoder, then we end up with duplicate column names. 

One solution could be that when we collapse multi-index, we concatenate the first level and second level to form new column names. A less desired solution could be not collapse_index here.

**Comment by jichaogp** [comment]
@jichaogp to verify this has been fixed.

**Comment by jichaogp** [comment]
I confirm this has been fixed with the following test case:

```python

def test_preprocessor_hashencoder_no_name_collision():
    import uuid
    import numpy as np
    import pandas as pd
    from foreshadow.preprocessor import Preprocessor

    cat1 = [uuid.uuid4() for _ in range(40)]
    cat2 = [uuid.uuid4() for _ in range(40)]

    input = pd.DataFrame({
        'col1': np.random.choice(cat1, 1000),
        'col2': np.random.choice(cat2, 1000)
    })

    processor = Preprocessor()
    output = processor.fit_transform(input)
    # since the number of categories for each column are above 30, HashingEncoder will be used with 30 components. The transformed
    # output should have in total 60 unique names.
    assert len(set(output.columns)) == 60
```

I cannot add this test case to code base yet. It seems DropFeatures are included for CategoricalIntent but does not work for Categorical features. I will provide more details in issue #1.

**Comment by jichaogp** [comment]
Will close this after I can commit the unit test case.

**Comment by adithyabsk** [comment]
I simplified the test case in issue #17 and added it at the transformer scope, can this issue be closed?
