### ISSUE TITLE
SmartTransformer's parameter should be in constructor

### ISSUE THREAD

**Issue by jichaogp** [georgianpartners/foreshadow#9]
https://github.com/georgianpartners/foreshadow/blob/12777dd018b14a2d03b7efd88a99db8d6bcdb819/foreshadow/transformers/smart.py#L32

Since intent does not call _get_transformer directly, it won't have a way to overwrite the default value for its parameters. These parameters should be moved to the corresponding constructor so that intent can customize them when creating the pipelines.

**Comment by jichaogp** [comment]
@robocoder99, the solution you mentioned earlier allow us to pass some parameters to the concrete transformer the SmartTransformer selected by passing the kwargs to fit() and transform() of the concrete transformer. However it does not allow the intent to control the behavior how SmartTransformer choose concrete transformers. In the following example, I would like to set the 'unique_num_cutoff' parameter used by Encoder from 30 to 35. This kwargs was not passed to Encoder's _get_transformer().

On the other hand, SimpleImputer has its 'threshold' parameter defined in constructor.


```python
def test_smart_encoder_more_than_30_levels_with_overwritten_cutoff():
    import numpy as np

    from foreshadow.transformers.smart import Encoder
    from foreshadow.transformers.internals import OneHotEncoder

    np.random.seed(0)
    gt_30_random_data = np.random.choice(31, size=500)
    smart_coder = Encoder(unique_num_cutoff=35)
    assert isinstance(smart_coder.fit(gt_30_random_data), OneHotEncoder)
```

**Comment by robocoder99** [comment]
I see what you mean, the way I had done it was implement an init method when neccesary to pass the required parameters. For the sake of ease of creation of smart transformers I will default to passing those kwargs. That should not cause any issues.
